services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - backend-venv:/app/.venv
    networks:
      - whatwedoin-network

networks:
  whatwedoin-network:
    external: true

volumes:
  backend-venv:
